# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.

# The site blueprint usually provides easy access to all main pages of the site.
# In this example blueprint, we also show subpages of the `photography` and `notes` pages.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

# The layout of this form has two columns:
columns:
  
  
  - width: 1/2
    sections:

      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - contact
          - default
      
      works: sections/works

  - width: 1/2
    fields:

      footer:
        type: textarea